######################################################################
# Copyright 2016, 2024 John J. Rofrano. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
######################################################################

"""
TestProduct API Service Test Suite
"""

# pylint: disable=duplicate-code
import os
import logging
from unittest import TestCase
from wsgi import app
from service.common import status
from service.models import DataValidationError, db, Product
from .factories import ProductFactory
from service.common.error_handlers import (
    bad_request,
    mediatype_not_supported,
    internal_server_error,
    request_validation_error,
)

DATABASE_URI = os.getenv(
    "DATABASE_URI", "postgresql+psycopg://postgres:postgres@localhost:5432/testdb"
)


######################################################################
#  T E S T   C A S E S
######################################################################
# pylint: disable=too-many-public-methods
class TestProductService(TestCase):
    """REST API Server Tests"""

    @classmethod
    def setUpClass(cls):
        """Run once before all tests"""
        app.config["TESTING"] = True
        app.config["DEBUG"] = False
        # Set up the test database
        app.config["SQLALCHEMY_DATABASE_URI"] = DATABASE_URI
        app.logger.setLevel(logging.CRITICAL)
        app.app_context().push()

    @classmethod
    def tearDownClass(cls):
        """Run once after all tests"""
        db.session.close()

    def setUp(self):
        """Runs before each test"""
        self.client = app.test_client()
        db.session.query(Product).delete()  # clean up the last tests
        db.session.commit()

    def tearDown(self):
        """This runs after each test"""
        db.session.remove()

    ######################################################################
    #  P L A C E   T E S T   C A S E S   H E R E
    ######################################################################

    def test_index(self):
        """It should call the home page"""
        resp = self.client.get("/")
        self.assertEqual(resp.status_code, status.HTTP_200_OK)

    def test_404_not_found(self):
        """It should return 404 for an unknown route"""
        resp = self.client.get("/nonexistent-route")
        self.assertEqual(resp.status_code, status.HTTP_404_NOT_FOUND)

    def test_405_method_not_allowed(self):
        """It should return 405 when using a disallowed HTTP method"""
        resp = self.client.post("/")
        self.assertEqual(resp.status_code, status.HTTP_405_METHOD_NOT_ALLOWED)

    def test_bad_request_handler(self):
        """It should return 400 for a bad request"""
        resp, status_code = bad_request(Exception("bad data"))
        self.assertEqual(status_code, status.HTTP_400_BAD_REQUEST)

    def test_mediatype_not_supported_handler(self):
        """It should return 415 for unsupported media type"""
        resp, status_code = mediatype_not_supported(Exception("unsupported media type"))
        self.assertEqual(status_code, status.HTTP_415_UNSUPPORTED_MEDIA_TYPE)

    def test_internal_server_error_handler(self):
        """It should return 500 for internal server error"""
        resp, status_code = internal_server_error(Exception("server error"))
        self.assertEqual(status_code, status.HTTP_500_INTERNAL_SERVER_ERROR)

    def test_data_validation_error_handler(self):
        """It should return 400 for DataValidationError"""
        resp, status_code = request_validation_error(DataValidationError("test error"))
        self.assertEqual(status_code, status.HTTP_400_BAD_REQUEST)

    ######################################################################
    #  P R O D U C T   R O U T E   T E S T   C A S E S
    ######################################################################

    def test_create_product_success(self):
        """It should create a Product and return 201"""
        product = ProductFactory()
        payload = product.serialize()
        payload.pop("id", None)  # id is generated by the database

        resp = self.client.post("/products", json=payload)
        self.assertEqual(resp.status_code, status.HTTP_201_CREATED)

        data = resp.get_json()
        self.assertIsNotNone(data)
        self.assertIsNotNone(data.get("id"))
        self.assertEqual(data["name"], payload["name"])
        self.assertEqual(data["description"], payload["description"])
        self.assertEqual(data["price"], payload["price"])
        self.assertEqual(data["category"], payload["category"])
        self.assertEqual(data["available"], payload["available"])

    def test_create_product_missing_required_field(self):
        """It should return 400 for missing required fields"""
        payload = {
            "description": "missing name",
            "price": "9.99",
            "category": "test",
        }

        resp = self.client.post("/products", json=payload)
        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)

        data = resp.get_json()
        self.assertIsNotNone(data)
        self.assertEqual(data["error"], "Bad Request")
        self.assertIn("missing", data["message"])

    def test_create_product_wrong_content_type(self):
        """It should return 415 for non-JSON content types"""
        resp = self.client.post(
            "/products",
            data="not json",
            content_type="text/plain",
        )
        self.assertEqual(resp.status_code, status.HTTP_415_UNSUPPORTED_MEDIA_TYPE)

    def test_create_product_empty_json_body(self):
        """It should return 400 for empty or invalid JSON bodies"""
        resp = self.client.post(
            "/products",
            data="",
            content_type="application/json",
        )
        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)

        data = resp.get_json()
        self.assertIsNotNone(data)
        self.assertEqual(data["error"], "Bad Request")
