######################################################################
# Copyright 2016, 2024 John J. Rofrano. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
######################################################################

"""
TestProduct API Service Test Suite
"""

# pylint: disable=duplicate-code
import os
import logging
from unittest import TestCase
from wsgi import app
from service.common import status
from service.models import DataValidationError, db, Product
from service.common.error_handlers import (
    bad_request,
    mediatype_not_supported,
    internal_server_error,
    request_validation_error,
)
from .factories import ProductFactory

DATABASE_URI = os.getenv("DATABASE_URI", "sqlite:///test.db")


######################################################################
#  T E S T   C A S E S
######################################################################
# pylint: disable=too-many-public-methods
class TestProductService(TestCase):
    """REST API Server Tests"""

    @classmethod
    def setUpClass(cls):
        """Run once before all tests"""
        app.config["TESTING"] = True
        app.config["DEBUG"] = False
        # Set up the test database
        app.config["SQLALCHEMY_DATABASE_URI"] = DATABASE_URI
        app.logger.setLevel(logging.CRITICAL)
        app.app_context().push()

    @classmethod
    def tearDownClass(cls):
        """Run once after all tests"""
        db.session.close()

    def setUp(self):
        """Runs before each test"""
        self.client = app.test_client()
        db.session.query(Product).delete()  # clean up the last tests
        db.session.commit()

    def tearDown(self):
        """This runs after each test"""
        db.session.remove()

    ######################################################################
    #  P L A C E   T E S T   C A S E S   H E R E
    ######################################################################

    def test_index(self):
        """It should call the home page"""
        response = self.client.get("/")
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.content_type, "application/json")
        data = response.get_json()
        self.assertIn("name", data)
        self.assertIn("version", data)
        self.assertIn("paths", data)
        self.assertEqual(data["name"], "Product Catalog Service")
        self.assertEqual(data["version"], "1.0")
        self.assertIsInstance(data["paths"], list)

    def test_404_not_found(self):
        """It should return 404 for an unknown route"""
        resp = self.client.get("/nonexistent-route")
        self.assertEqual(resp.status_code, status.HTTP_404_NOT_FOUND)

    def test_405_method_not_allowed(self):
        """It should return 405 when using a disallowed HTTP method"""
        resp = self.client.post("/")
        self.assertEqual(resp.status_code, status.HTTP_405_METHOD_NOT_ALLOWED)

    def test_bad_request_handler(self):
        """It should return 400 for a bad request"""
        resp, status_code = bad_request(Exception("bad data"))
        self.assertEqual(status_code, status.HTTP_400_BAD_REQUEST)

    def test_mediatype_not_supported_handler(self):
        """It should return 415 for unsupported media type"""
        resp, status_code = mediatype_not_supported(Exception("unsupported media type"))
        self.assertEqual(status_code, status.HTTP_415_UNSUPPORTED_MEDIA_TYPE)

    def test_internal_server_error_handler(self):
        """It should return 500 for internal server error"""
        resp, status_code = internal_server_error(Exception("server error"))
        self.assertEqual(status_code, status.HTTP_500_INTERNAL_SERVER_ERROR)

    def test_data_validation_error_handler(self):
        """It should return 400 for DataValidationError"""
        resp, status_code = request_validation_error(DataValidationError("test error"))
        self.assertEqual(status_code, status.HTTP_400_BAD_REQUEST)

    ######################################################################
    #  P R O D U C T   R O U T E   T E S T   C A S E S
    ######################################################################

    def test_create_product_success(self):
        """It should create a Product and return 201"""
        product = ProductFactory()
        payload = product.serialize()
        payload.pop("id", None)  # id is generated by the database

        resp = self.client.post("/products", json=payload)
        self.assertEqual(resp.status_code, status.HTTP_201_CREATED)

        data = resp.get_json()
        self.assertIsNotNone(data)
        self.assertIsNotNone(data.get("id"))
        self.assertEqual(data["name"], payload["name"])
        self.assertEqual(data["description"], payload["description"])
        self.assertEqual(data["price"], payload["price"])
        self.assertEqual(data["category"], payload["category"])
        self.assertEqual(data["available"], payload["available"])

    def test_create_product_missing_required_field(self):
        """It should return 400 for missing required fields"""
        payload = {
            "description": "missing name",
            "price": "9.99",
            "category": "test",
        }

        resp = self.client.post("/products", json=payload)
        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)

        data = resp.get_json()
        self.assertIsNotNone(data)
        self.assertEqual(data["error"], "Bad Request")
        self.assertIn("missing", data["message"])

    def test_create_product_wrong_content_type(self):
        """It should return 415 for non-JSON content types"""
        resp = self.client.post(
            "/products",
            data="not json",
            content_type="text/plain",
        )
        self.assertEqual(resp.status_code, status.HTTP_415_UNSUPPORTED_MEDIA_TYPE)

    def test_create_product_empty_json_body(self):
        """It should return 400 for empty or invalid JSON bodies"""
        resp = self.client.post(
            "/products",
            data="",
            content_type="application/json",
        )
        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)

        data = resp.get_json()
        self.assertIsNotNone(data)
        self.assertEqual(data["error"], "Bad Request")

    def test_get_product_success(self):
        """It should retrieve a Product and return 200"""
        product = ProductFactory()
        payload = product.serialize()
        payload.pop("id", None)

        create_resp = self.client.post("/products", json=payload)
        self.assertEqual(create_resp.status_code, status.HTTP_201_CREATED)
        created = create_resp.get_json()
        self.assertIsNotNone(created)
        product_id = created["id"]

        resp = self.client.get(f"/products/{product_id}")
        self.assertEqual(resp.status_code, status.HTTP_200_OK)

        data = resp.get_json()
        self.assertIsNotNone(data)
        self.assertEqual(data["id"], product_id)
        self.assertEqual(data["name"], payload["name"])
        self.assertEqual(data["description"], payload["description"])
        self.assertEqual(data["price"], payload["price"])
        self.assertEqual(data["category"], payload["category"])
        self.assertEqual(data["available"], payload["available"])

    def test_list_products(self):
        """It should list all Products"""
        products = ProductFactory.create_batch(3)
        for product in products:
            payload = product.serialize()
            payload.pop("id", None)
            resp = self.client.post("/products", json=payload)
            self.assertEqual(resp.status_code, status.HTTP_201_CREATED)

        resp = self.client.get("/products")
        self.assertEqual(resp.status_code, status.HTTP_200_OK)
        self.assertEqual(resp.content_type, "application/json")

        data = resp.get_json()
        self.assertEqual(len(data), 3)

    def test_get_product_not_found(self):
        """It should return 404 when Product does not exist"""
        resp = self.client.get("/products/999999")
        self.assertEqual(resp.status_code, status.HTTP_404_NOT_FOUND)

        data = resp.get_json()
        self.assertIsNotNone(data)
        self.assertEqual(data["error"], "Not Found")
        self.assertIn("Product with id", data["message"])

    def test_get_product_invalid_id_format(self):
        """It should return 400 when id format is invalid"""
        resp = self.client.get("/products/abc")
        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)

        data = resp.get_json()
        self.assertIsNotNone(data)
        self.assertEqual(data["error"], "Bad Request")
        self.assertIn("must be an integer", data["message"])

    def test_update_product_success(self):
        """It should update an existing Product and return 200"""
        product = ProductFactory()
        payload = product.serialize()
        payload.pop("id", None)

        create_resp = self.client.post("/products", json=payload)
        self.assertEqual(create_resp.status_code, status.HTTP_201_CREATED)
        created = create_resp.get_json()
        product_id = created["id"]

        updated_data = created.copy()
        updated_data["name"] = "Updated Product Name"
        updated_data["price"] = 99.99

        resp = self.client.put(f"/products/{product_id}", json=updated_data)
        self.assertEqual(resp.status_code, status.HTTP_200_OK)

        data = resp.get_json()
        self.assertIsNotNone(data)
        self.assertEqual(data["id"], product_id)
        self.assertEqual(data["name"], "Updated Product Name")
        self.assertEqual(str(data["price"]), "99.99")

    def test_update_product_not_found(self):
        """It should return 404 when updating a Product that does not exist"""
        product = ProductFactory()
        payload = product.serialize()
        payload["id"] = 999999

        resp = self.client.put("/products/999999", json=payload)
        self.assertEqual(resp.status_code, status.HTTP_404_NOT_FOUND)

        data = resp.get_json()
        self.assertIsNotNone(data)
        self.assertEqual(data["error"], "Not Found")

    def test_update_product_invalid_id_format(self):
        """It should return 400 when update id format is invalid"""
        product = ProductFactory()
        payload = product.serialize()

        resp = self.client.put("/products/abc", json=payload)
        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)

        data = resp.get_json()
        self.assertIsNotNone(data)
        self.assertEqual(data["error"], "Bad Request")

    def test_update_product_wrong_content_type(self):
        """It should return 415 for non-JSON content types on update"""
        resp = self.client.put(
            "/products/1",
            data="not json",
            content_type="text/plain",
        )
        self.assertEqual(resp.status_code, status.HTTP_415_UNSUPPORTED_MEDIA_TYPE)

    def test_update_product_empty_json_body(self):
        """It should return 400 for empty update body"""
        product = ProductFactory()
        payload = product.serialize()
        payload.pop("id", None)

        create_resp = self.client.post("/products", json=payload)
        self.assertEqual(create_resp.status_code, status.HTTP_201_CREATED)
        created = create_resp.get_json()
        product_id = created["id"]

        resp = self.client.put(
            f"/products/{product_id}",
            data="",
            content_type="application/json",
        )
        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)

        data = resp.get_json()
        self.assertIsNotNone(data)
        self.assertEqual(data["error"], "Bad Request")

    def test_delete_product_success(self):
        """It should delete an existing Product and return 204"""
        product = ProductFactory()
        payload = product.serialize()
        payload.pop("id", None)

        create_resp = self.client.post("/products", json=payload)
        self.assertEqual(create_resp.status_code, status.HTTP_201_CREATED)
        created = create_resp.get_json()
        product_id = created["id"]

        resp = self.client.delete(f"/products/{product_id}")
        self.assertEqual(resp.status_code, status.HTTP_204_NO_CONTENT)

        get_resp = self.client.get(f"/products/{product_id}")
        self.assertEqual(get_resp.status_code, status.HTTP_404_NOT_FOUND)

    def test_delete_product_not_found(self):
        """It should return 404 when deleting a Product that does not exist"""
        resp = self.client.delete("/products/999999")
        self.assertEqual(resp.status_code, status.HTTP_404_NOT_FOUND)

        data = resp.get_json()
        self.assertIsNotNone(data)
        self.assertEqual(data["error"], "Not Found")

    def test_delete_product_invalid_id_format(self):
        """It should return 400 when delete id format is invalid"""
        resp = self.client.delete("/products/abc")
        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)

        data = resp.get_json()
        self.assertIsNotNone(data)
        self.assertEqual(data["error"], "Bad Request")
