apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-sa-binding
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-sa-clusterbinding
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-sa
    # Change "default" to your namespace before applying on OpenShift.
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cd-pipeline-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: github-push
      interceptors:
        - ref:
            name: cel
          params:
            - name: filter
              value: "header.match('X-GitHub-Event', 'push') && body.ref == 'refs/heads/master'"
            - name: overlays
              value:
                - key: branch_name
                  expression: "body.ref.split('/')[2]"
      bindings:
        - ref: github-push-binding
      template:
        ref: cd-pipeline-template
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cd-pipeline-listener
spec:
  to:
    kind: Service
    name: el-cd-pipeline-listener
  port:
    targetPort: http-listener
