apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone
    - name: branch
      type: string
      description: The git branch to clone
      default: master
    - name: image-name
      type: string
      description: The image to build and deploy
      default: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/products:latest

  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
        - name: deleteExisting      
          value: "true"  
    - name: lint
      runAfter:
        - clone
      taskRef:
        name: lint
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: tests
      runAfter:
        - clone
      taskRef:
        name: tests
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: build
      runAfter:
        - lint
        - tests
      taskRef:
        name: build
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: IMAGE_NAME
          value: $(params.image-name)

    - name: deploy
      runAfter:
        - build
      taskRef:
        name: deploy
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: IMAGE_NAME
          value: $(params.image-name)

    - name: bdd
      runAfter:
        - deploy
      taskRef:
        name: bdd
      workspaces:
        - name: source
          workspace: pipeline-workspace
