apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-workspace
  labels:
    app.kubernetes.io/name: pipeline-workspace
    app.kubernetes.io/part-of: products
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
